### PR TITLE
Hotfix/custom loader

### PR DESCRIPTION
**Pull request by Abhijeetjaiswalit**
Sorry for the delay, as i'm not so comfortable with command line of GIT. Check now if you can go ahead with this.

### CODE REVIEW

**Comment by varunon9** [comment]
one PR should have only one commit else it will pollute commit log history. This PR had 4 commits but I squashed it on my end.

**Comment by Abhijeetjaiswalit** [comment]
Thank you so much. 😊

**Comment by Abhijeetjaiswalit** [comment]
Heyy! question => why cant i use the updated package(by fresh installing
your repo?). I tried clean installing your library `yarn
add react-native-toggle-calendar`

still i see the old code.

**Comment by varunon9** [comment]
i'll make a release on nom and update you or you can install using github
repo url.

**Comment by varunon9** [comment]
v1.0.3 is available on npm with the fix.

Thanks,
Varun Kumar

**Comment by Abhijeetjaiswalit** [comment]
Thank you so much😊

**Pull request merged**
